### ISSUE TITLE
Multi Match Query

### ISSUE THREAD

**Issue by magedan** [sonata-project/SonataAdminSearchBundle#9]
Could you please provide any recommendation for the best way to implement Multi Match Elastica query?

Basically, I need almost the same functionality as `StringFilter` has, with minor difference. Right now `StringFilter` uses \Elastica\Query\Builder in the following way:

``` php
$queryBuilder = new \Elastica\Query\Builder();
$queryBuilder
    ->fieldOpen($secondOperator)
        ->fieldOpen($field)
            ->field('query', Util::escapeTerm($data['value']))
            ->field('operator', 'and')
        ->fieldClose()
    ->fieldClose();
```

And I want something like this:

``` php
$queryBuilder = new \Elastica\Query\Builder();
$queryBuilder
    ->fieldOpen('multi_match')
        ->field('query', Util::escapeTerm($data['value']))
        ->field('fields', /* fields from filter parameters, maybe? */)
        ->field('operator', 'and')
    ->fieldClose();
```

**Comment by greg0ire** [comment]
I am sorry, I really don't know… is this supposed to match the search term against several fields ? Not sure what you are trying to do…

**Comment by magedan** [comment]
I have following indexes config:

``` yaml
fos_elastica:
    indexes:
        my_index:
            settings:
                index:
                    analysis:
                        analyzer:
                            name_ngram:
                                type:           custom
                                tokenizer:      letter
                                filter:         [lowercase, asciifolding, synonym, ngram]
                            name_std:
                                type:           custom
                                tokenizer:      letter
                                filter:         [lowercase, asciifolding, synonym]
                        filter:
                            synonym:
                                type:           synonym
                                synonyms_path:  "%elastica_synonyms%"
                            ngram:
                                type:           edge_ngram
                                min_gram:       3
                                max_gram:       20
            types:
                my_type:
                    mappings:
                        name:
                            type:               string
                            index_analyzer:     name_ngram
                            search_analyzer:    name_std
                            fields:
                                std:
                                    type:       string
                                    analyzer:   name_std
#                        ...
```

Due to business requirements (search algorithm) I have to use two different index analyzers and try to find document using both of them. Here is the sample of the query which is used in the application's API:

``` json
{"query":{"multi_match":{"fields":["name","name.std"],"operator":"and","query":"search string"}},"from":0,"size":100}
```

I realized, that this is very special case and there is no need to create specific filter for that. Probably, I should try to implement CallbackFilter.
